version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5103:80"
      - "5101:443"

  catalogservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DefaultConnection=Data Source=host.docker.internal;Initial Catalog=CatalogService;Integrated Security=False;User ID=sa;Password=pass@word1;TrustServerCertificate=True
    ports:
      - "5104:80"
      - "5108:443"

  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DefaultConnection=Data Source=host.docker.internal;Initial Catalog=OrderService;Integrated Security=False;User ID=sa;Password=pass@word1;TrustServerCertificate=True
    ports:
      - "5105:80"
      - "5109:443"

  # sqldata:
  #   environment:
  #     - SA_PASSWORD=pass@word1
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "5433:1433"